package s1ap

const (
	S1_SETUP_REQUEST = iota + 1
	S1_SETUP_RESPONSE
	INITIAL_UE_MESSAGE
	INITIAL_CONTEXT_SETUP_REQUEST
	UPLINK_NAS_TRANSPORT
	DOWNLINK_NAS_TRANSPORT
	ERROR_INDICATION
)

const (
	NAS_EPS_AUTH_RESPONSE = iota + 1
	NAS_EPS_SECURITY_MODE_COMPLETE
)

const (
	NAS_EPS_MOBILITY_MANAGEMENT_MESSAGE_TYPE_ATTACH_REJECT = 0x44
)
